# Generated by Django 3.2.7 on 2023-07-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=150)),
                ('tender_number', models.IntegerField()),
                ('publishing_date', models.DateField(blank=True)),
                ('file_upload_status', models.CharField(choices=[('FILE UPLOADED', 'FILE UPLOADED'), ('FILE UPLOADING', 'FILE UPLOADING'), ('NO FILE UPLOADED', 'NO FILE UPLOADED')], max_length=150)),
                ('tender_status', models.CharField(choices=[('SUCCEEDED', 'SUCCEEDED'), ('UPLOADING', 'UPLOADING'), ('NO FILE UPLOADED', 'NO FILE UPLOADED'), ('PROCESSING', 'PROCESSING')], max_length=150)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.division')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_date', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_date', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
