# Generated by Django 3.2.7 on 2023-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_tenderdetail_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetail',
            name='publishing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
