# Generated by Django 3.2.7 on 2023-07-04 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_tenderdetail_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetail',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_date', to=settings.AUTH_USER_MODEL),
        ),
    ]
