# Generated by Django 3.2.7 on 2023-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_tenderdetail_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetail',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
