# Generated by Django 3.2.18 on 2023-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_user_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superUser',
            field=models.BooleanField(default=False),
        ),
    ]
