# Generated by Django 3.2.18 on 2023-11-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superUser',
            new_name='super_admin',
        ),
    ]
